import { Phoneme } from "./types"
export function phonesToFeatures(phones: string | string[]): Phoneme[] {
  if (typeof phones === "string") {
    phones = phones.split("")
  }
  return phones.map(c => {
    if (c in phonemes) return phonemes[c]
    else {
      throw new Error(`No feature data for phone ${c}`)
    }
  })
}
export let phonemes: Record<string, Phoneme> = {
  p: { cons: true, son: false, place: "labial", voice: false, contin: false, approx: false },
  b: { cons: true, son: false, place: "labial", voice: true, contin: false, approx: false },
  t: { cons: true, son: false, place: "coronal", voice: false, contin: false, approx: false, anterior: true },
  d: { cons: true, son: false, place: "coronal", voice: true, contin: false, approx: false, anterior: true },
  ʈ: { cons: true, son: false, place: "coronal", voice: false, contin: false, approx: false, anterior: false },
  ɖ: { cons: true, son: false, place: "coronal", voice: true, contin: false, approx: false, anterior: false },
  c: { cons: true, son: false, place: "coronal", voice: false, contin: false, approx: false, anterior: false },
  ɟ: { cons: true, son: false, place: "coronal", voice: true, contin: false, approx: false, anterior: false },
  k: { cons: true, son: false, place: "dorsal", voice: false, contin: false, approx: false, back: true },
  g: { cons: true, son: false, place: "dorsal", voice: true, contin: false, approx: false, back: true },
  q: { cons: true, son: false, place: "dorsal", voice: false, contin: false, approx: false, back: true },
  ɢ: { cons: true, son: false, place: "dorsal", voice: true, contin: false, approx: false, back: true },
  ʔ: {
    cons: true,
    son: false,
    place: "dorsal",
    voice: true,
    contin: false,
    approx: false,
    back: true,
    "constr gl": true,
  },
  //row 1 FINISH!
  m: { cons: true, son: true, place: "labial", voice: true, nasal: true, contin: false, approx: false },
  ɱ: { cons: true, son: true, place: "labial", voice: true, nasal: true, contin: false, approx: false },
  n: {
    cons: true,
    son: true,
    place: "coronal",
    voice: true,
    nasal: true,
    contin: false,
    approx: false,
    anterior: true,
  },
  ɳ: {
    cons: true,
    son: true,
    place: "coronal",
    voice: true,
    nasal: true,
    contin: false,
    approx: false,
    anterior: false,
  },
  ɲ: {
    cons: true,
    son: true,
    place: "coronal",
    voice: true,
    nasal: true,
    contin: false,
    approx: false,
    anterior: false,
  },
  ŋ: { cons: true, son: true, place: "dorsal", voice: true, nasal: true, contin: false, approx: false },
  ɴ: { cons: true, son: true, place: "dorsal", voice: true, nasal: true, contin: false, approx: false },
  //row 2 FINISH!
  ʙ: { cons: true, son: true, place: "labial", voice: true, contin: true, approx: true, lateral: false },
  r: { cons: true, son: true, place: "coronal", voice: true, contin: true, approx: true, lateral: false },
  ʀ: { cons: true, son: true, place: "dorsal", voice: true, contin: true, approx: true, lateral: false },
  //row 3 FINISH!
  ɾ: {
    cons: true,
    son: true,
    place: "coronal",
    voice: true,
    contin: false,
    approx: true,
    lateral: false,
    anterior: true,
  },
  ɽ: {
    cons: true,
    son: true,
    place: "coronal",
    voice: true,
    contin: false,
    approx: true,
    lateral: false,
    anterior: false,
  },
  //row 4 FINISH!
  ɸ: { cons: true, son: false, place: "labial", voice: false, approx: false, contin: true, strid: false },
  β: { cons: true, son: false, place: "labial", voice: true, approx: false, contin: true, strid: false },
  f: { cons: true, son: false, place: "labial", voice: false, approx: false, contin: true, strid: true },
  v: { cons: true, son: false, place: "labial", voice: true, approx: false, contin: true, strid: true },
  θ: {
    cons: true,
    son: false,
    place: "coronal",
    voice: false,
    approx: false,
    contin: true,
    strid: false,
    anterior: true,
  },
  ð: {
    cons: true,
    son: false,
    place: "coronal",
    voice: true,
    approx: false,
    contin: true,
    strid: false,
    anterior: true,
  },
  s: {
    cons: true,
    son: false,
    place: "coronal",
    voice: false,
    approx: false,
    contin: true,
    strid: true,
    anterior: true,
  },
  z: {
    cons: true,
    son: false,
    place: "coronal",
    voice: true,
    approx: false,
    contin: true,
    strid: true,
    anterior: true,
  },
  ʃ: {
    cons: true,
    son: false,
    place: "coronal",
    voice: false,
    approx: false,
    contin: true,
    strid: true,
    anterior: false,
  },
  ʒ: {
    cons: true,
    son: false,
    place: "coronal",
    voice: true,
    approx: false,
    contin: true,
    strid: true,
    anterior: false,
  },
  ʂ: {
    cons: true,
    son: false,
    place: "coronal",
    voice: false,
    approx: false,
    contin: true,
    strid: true,
    anterior: false,
  },
  ʐ: {
    cons: true,
    son: false,
    place: "coronal",
    voice: true,
    approx: false,
    contin: true,
    strid: true,
    anterior: false,
  },
  ç: {
    cons: true,
    son: false,
    place: "coronal",
    voice: false,
    approx: false,
    contin: true,
    strid: true,
    anterior: false,
  },
  ʝ: {
    cons: true,
    son: false,
    place: "coronal",
    voice: true,
    approx: false,
    contin: true,
    strid: true,
    anterior: false,
  },
  x: { cons: true, son: false, place: "dorsal", voice: false, approx: false, contin: true, strid: false },
  ɣ: { cons: true, son: false, place: "dorsal", voice: true, approx: false, contin: true, strid: false },
  χ: { cons: true, son: false, place: "dorsal", voice: false, approx: false, contin: true, strid: true },
  ʁ: { cons: true, son: false, place: "dorsal", voice: true, approx: false, contin: true, strid: true },
  ħ: { cons: true, son: false, place: "dorsal", voice: false, approx: false, contin: true, strid: false, RTR: true },
  ʕ: { cons: true, son: false, place: "dorsal", voice: true, approx: false, contin: true, strid: false, RTR: true },
  h: { cons: true, son: false, place: "dorsal", voice: false, approx: false, contin: true, strid: true },
  ɦ: { cons: true, son: false, place: "dorsal", voice: true, approx: false, contin: true, strid: true },
  //row 5 FINISH!
  ɬ: {
    cons: true,
    son: false,
    place: "coronal",
    voice: false,
    contin: true,
    approx: true,
    anterior: true,
    lateral: true,
  },
  ɮ: {
    cons: true,
    son: false,
    place: "coronal",
    voice: true,
    contin: true,
    approx: true,
    anterior: true,
    lateral: true,
  },
  //row 6 FINISH!
  ʋ: { cons: true, son: true, place: "labial", voice: true, contin: true, approx: true, lateral: false },
  ɹ: {
    cons: true,
    son: true,
    place: "coronal",
    voice: true,
    contin: true,
    approx: true,
    anterior: true,
    lateral: false,
  },
  ɻ: {
    cons: true,
    son: true,
    place: "coronal",
    voice: true,
    contin: true,
    approx: true,
    anterior: false,
    lateral: false,
  },
  j: {
    cons: true,
    son: true,
    place: "coronal",
    voice: true,
    contin: true,
    approx: true,
    anterior: false,
    lateral: false,
  },
  ɰ: { cons: true, son: true, place: "dorsal", voice: true, contin: true, approx: true, lateral: false },
  //row 7 FINISH!
  l: {
    cons: true,
    son: true,
    place: "coronal",
    voice: true,
    contin: true,
    approx: true,
    anterior: true,
    lateral: true,
  },
  ɭ: {
    cons: true,
    son: true,
    place: "coronal",
    voice: true,
    contin: true,
    approx: true,
    anterior: false,
    lateral: true,
  },
  ʎ: {
    cons: true,
    son: true,
    place: "coronal",
    voice: true,
    contin: true,
    approx: true,
    anterior: false,
    lateral: true,
  },
  ʟ: { cons: true, son: true, place: "dorsal", voice: true, contin: true, approx: true, lateral: true },
  //row 8 FINISH!
  //vowel-part BEGIN!
  a: {
    cons: false,
    son: true,
    high: false,
    low: true,
    back: false,
    ATR: false,
    round: false,
    approx: true,
    contin: true,
  },
  ʌ: {
    cons: false,
    son: true,
    high: false,
    low: false,
    back: true,
    ATR: true,
    round: false,
    approx: true,
    contin: true,
  },
  ɔ: {
    cons: false,
    son: true,
    high: false,
    low: false,
    back: true,
    ATR: false,
    round: true,
    approx: true,
    contin: true,
  },
  o: {
    cons: false,
    son: true,
    high: false,
    low: false,
    back: true,
    ATR: true,
    round: true,
    approx: true,
    contin: true,
  },
  ɯ: {
    cons: false,
    son: true,
    high: true,
    low: false,
    back: true,
    ATR: true,
    round: false,
    approx: true,
    contin: true,
  },
  u: { cons: false, son: true, high: true, low: false, back: true, ATR: true, round: true, approx: true, contin: true },
  ʊ: {
    cons: false,
    son: true,
    high: true,
    low: false,
    back: true,
    ATR: false,
    round: true,
    approx: true,
    contin: true,
  },
  ɨ: {
    cons: false,
    son: true,
    high: true,
    low: false,
    back: true,
    ATR: false,
    round: false,
    approx: true,
    contin: true,
  },
  ə: {
    cons: false,
    son: true,
    high: false,
    low: false,
    back: true,
    ATR: false,
    round: false,
    approx: true,
    contin: true,
  },
  i: {
    cons: false,
    son: true,
    high: true,
    low: false,
    back: false,
    ATR: true,
    round: false,
    approx: true,
    contin: true,
  },
  y: {
    cons: false,
    son: true,
    high: true,
    low: false,
    back: false,
    ATR: true,
    round: true,
    approx: true,
    contin: true,
  },
  ɪ: {
    cons: false,
    son: true,
    high: true,
    low: false,
    back: false,
    ATR: false,
    round: false,
    approx: true,
    contin: true,
  },
  e: {
    cons: false,
    son: true,
    high: false,
    low: false,
    back: false,
    ATR: true,
    round: false,
    approx: true,
    contin: true,
  },
  ø: {
    cons: false,
    son: true,
    high: false,
    low: false,
    back: false,
    ATR: true,
    round: true,
    approx: true,
    contin: true,
  },
  ɛ: {
    cons: false,
    son: true,
    high: false,
    low: false,
    back: false,
    ATR: false,
    round: false,
    approx: true,
    contin: true,
  },
  œ: {
    cons: false,
    son: true,
    high: false,
    low: false,
    back: false,
    ATR: false,
    round: true,
    approx: true,
    contin: true,
  },
  æ: {
    cons: false,
    son: true,
    high: false,
    low: true,
    back: false,
    ATR: false,
    round: false,
    approx: true,
    contin: true,
  },
  // extended things (prompted by S** transcriptions)
  // need a 3rd attr 'mid' in addition to 'high' and 'low' for ɜ
  ɜ: {
    cons: false,
    son: true,
    high: false,
    low: false,
    back: true,
    ATR: false,
    round: false,
    approx: true,
    contin: true,
  },
  ɒ: {
    cons: false,
    son: true,
    high: false,
    low: true,
    back: true,
    ATR: false,
    round: true,
    approx: true,
    contin: true,
  },
  ɑ: {
    cons: false,
    son: true,
    high: false,
    low: true,
    back: true,
    ATR: false,
    round: false,
    approx: true,
    contin: true,
  },
  ʉ: {
    cons: false,
    son: true,
    high: true,
    low: false,
    back: true,
    ATR: false,
    round: true,
    approx: true,
    contin: true,
  },
  ʏ: {
    cons: false,
    son: true,
    high: true,
    low: false,
    back: false,
    ATR: false,
    round: true,
    approx: true,
    contin: true,
  },
  w: {
    cons: true,
    son: true,
    place: "labial",
    voice: true,
    contin: true,
    approx: true,
    anterior: true,
    lateral: false,
  },
  ʰ: { cons: true, son: false, place: "dorsal", voice: false, approx: false, contin: true, strid: true },
  ɫ: {
    cons: true,
    son: true,
    place: "dorsal",
    voice: true,
    contin: true,
    approx: true,
    anterior: false,
    lateral: true,
  },
  "#": { boundary: true },
} //last (but not least), a concession to reality
